version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    env_file:
      - .env

# mongodb atlas 는 로컬 컨테이너 필요없음. 환경변수로 넘겨주기기